### ISSUE TITLE
Running Minetest with Docker Compose error/problem

### ISSUE THREAD

**Issue by pietru2004** [minetest/minetest#13816]
Hello I have been trying to run Minetest server using docker compose but I get following error:
![obraz](https://github.com/minetest/minetest/assets/51274570/1d2c241d-ec23-400f-bd1a-54523b0150f3)

My Docker Compose:
```
version: '3.7'
services:
  minetest:
    image: registry.gitlab.com/minetest/minetest/server:master
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/minetest
      - ./conf:/etc/minetest
    #environment:
    #  gameid: "1"
    #  worldname: "World"
    ports:
      - 25564:25564
```

I launch docker-compose in empty directory (if you exclude docker-compose.yaml)

Would somebody be able to help how to run it?
Also could there be created example docker-compose?

**Comment by sfan5** [comment]
please see https://github.com/minetest/minetest/issues/13613#issuecomment-1604695672
does this solve your issue?

**Comment by pietru2004** [comment]
@sfan5 folders were created by docker which normaly gives required permissions
Folders had
![obraz](https://github.com/minetest/minetest/assets/51274570/ca5e2803-4930-432a-9e15-28e082819d8c)
I changed it to
![obraz](https://github.com/minetest/minetest/assets/51274570/bc35ed3b-bc9b-4950-9911-e6856dedc7d3)
It did not change anything and problem still persists...

**Comment by sfan5** [comment]
I had a mistake in that comment, try to change the owner to uid 30000 instead (same command but with `chown`).

**Comment by pietru2004** [comment]
@sfan5 now it works... and now I have question is there way to make it work with root as owner, cause docker normaly changes owner to root

**Comment by pietru2004** [comment]
also it might me doing something wrong, but it does not allow me to connect to server, it timeouts, ports are open

**Comment by sfan5** [comment]
> is there way to make it work with root as owner, cause docker normaly changes owner to root

There isn't. And I'm not experienced with docker but I'm pretty sure it does not force a specific user for volumes.

> it does not allow me to connect to server

You have port 25564 in your docker-compose configuration, Minetest does not use this port. It uses 30000 (UDP).

**Comment by pietru2004** [comment]
ok I got to log into server...
I forgot to make docker compose line end with `/udp` otherwise it defaults to tcp

Also if for example ./data folder would not exist it would create folder root:root and I ask is there way to make minetest docker server work with that

**Comment by pietru2004** [comment]
also this is my current docker compose
```
version: '3.7'
services:
  minetest:
    image: registry.gitlab.com/minetest/minetest/server:master
    restart: unless-stopped
    command: "--verbose --port 25564"
    volumes:
      - ./data:/var/lib/minetest
      - ./conf:/etc/minetest
    #environment:
    #  port: 25564
    #  gameid: "1"
    #  worldname: "World"
    ports:
      - 25564:25564/udp
 ```
