### ISSUE TITLE
Server self closing without any info

### ISSUE THREAD

**Issue by pietru2004** [minetest/minetest#13837]
### Minetest version

```true
Minetest 5.8.0-dev - server
Minetest 5.7.9 - client
docker
```

### Operating system and version

Linux server - docker

### Summary

My server self closes without any info why it happens

I run minetest using docker compose file that looks like this
```
version: '3.7'
services:
  minetest:
    image: registry.gitlab.com/minetest/minetest/server:master
    restart: unless-stopped
    command: " --port 25564 --gameid minetest --world server_world_technic" #--verbose 
    volumes:
      - ./data:/var/lib/minetest
      - ./conf:/etc/minetest
    #environment:
    #  port: 25564
    #  gameid: "1"
    #  worldname: "World"
    ports:
      - 25564:25564/udp
   ```

Server world config
[world.txt](https://github.com/minetest/minetest/files/12706456/world.txt)
Server debug log
[debug.txt](https://github.com/minetest/minetest/files/12706457/debug.txt)

The part I mean is
![obraz](https://github.com/minetest/minetest/assets/51274570/a48502b1-fd36-488c-8326-d49355ac2f0c)
at this point I get `Access denied. Connection timeout.`
and I think it might be related to docker downloading dev version (I fought it would download stable version as I was following production server setup for docker part of running server)
Also running server with --verbose does not change anything, it still looks similar to log

### Steps to reproduce

Not sure...
