### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [minetest/minetest#14625]
### Minetest version

```true
5.8.1-android
```

### Operating system and version

Android

### Summary

trying to build, and since [there's no associated minetest_android_deps tag too](https://github.com/minetest/minetest_android_deps/issues/3#issuecomment-2100006568) I used HEAD (https://github.com/minetest/minetest_android_deps/commit/5dcfde6acde07788fb3b0ed340f472c31a79b7d3)

but it fails, log: [net.minetest.minetest_48.log.gz](https://github.com/minetest/minetest/files/15247517/net.minetest.minetest_48.log.gz)

am I missing some deps in the build VM?

Here's the full recipe:
```
  - versionName: 5.8.1-android
    versionCode: 48
    commit: d445638265886ed9f0ae680eebc18c976d7e5387
    subdir: android/app
    sudo:
      - echo "deb https://deb.debian.org/debian bullseye main" > /etc/apt/sources.list.d/bullseye.list
      - apt-get update
      - apt-get install -y cmake gcc-multilib gettext make wget xz-utils
      - apt-get install -y -t bullseye openjdk-11-jdk-headless
      - update-java-alternatives --set java-1.11.0-openjdk-amd64
    gradle:
      - yes
    srclibs:
      - minetest_android_deps@48ef4978ec967018991ef01fbdfc9c418fc67368
    prebuild: sed -i -e 's/enable true/enable false/' -e '/preBuild.dependsOn getDeps/d'
      build.gradle ../native/build.gradle
    build:
      - export ndkversion=$(grep "ndk_version = " ../build.gradle | cut -d "'" -f
        2)
      - sdkmanager "ndk;$ndkversion"
      - export ANDROID_NDK=$$SDK$$/ndk/$ndkversion
      - pushd $$minetest_android_deps$$
      - git checkout -f 5dcfde6acde07788fb3b0ed340f472c31a79b7d3
      - ./build.sh --all armeabi-v7a
      - ./build.sh --all arm64-v8a
      - ./build.sh --all x86
      - ./build.sh --all x86_64
      - popd
      - mv $$minetest_android_deps$$/deps ../native
```

### Steps to reproduce

-

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/f7b4143f0cb898a15376df8afd7bc555fa40d850
