### ISSUE TITLE
Android  Build is broken

### ISSUE THREAD

**Issue by zaoqi** [minetest/minetest#9158]
##### Minetest version

https://github.com/minetest/minetest/commit/4b6bff46e14c6215828da5ca9ad2cb79aa517a6e

##### Summary

Android  Build is broken

```
armeabi-v7a] Prebuilt       : libiconv.so <= jni/../deps/libiconv/lib/.libs/

[armeabi-v7a] Prebuilt       : libopenal.so <= jni/../deps/openal-soft/libs/armeabi-v7a/

[armeabi-v7a] Prebuilt       : libogg.so <= jni/../deps/libvorbis-libogg-android/libs/armeabi-v7a/

[armeabi-v7a] Prebuilt       : libvorbis.so <= jni/../deps/libvorbis-libogg-android/libs/armeabi-v7a/

[armeabi-v7a] Prebuilt       : libc++_shared.so <= <NDK>/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/

[armeabi-v7a] Compile thumb  : android_native_app_glue <= android_native_app_glue.c

[armeabi-v7a] StaticLibrary  : libandroid_native_app_glue.a

[armeabi-v7a] SharedLibrary  : libminetest.so

jni/../jni/src/gui/guiFormSpecMenu.cpp:1586: error: undefined reference to 'GUIHyperText::GUIHyperText(wchar_t const*, irr::gui::IGUIEnvironment*, irr::gui::IGUIElement*, int, irr::core::rect<int> const&, Client*, ISimpleTextureSource*)'

clang++: error: linker command failed with exit code 1 (use -v to see invocation)

make[2]: *** [obj/local/armeabi-v7a/libminetest.so] Error 1

make[2]: Leaving directory `/tmp/WORKSPACE/minetest/build/android'

Makefile:687: recipe for target 'apk' failed

make[1]: *** [apk] Error 1

make[1]: Leaving directory '/tmp/WORKSPACE/minetest/build/android'

Makefile:156: recipe for target 'release' failed

make: *** [release] Error 2

The command "make release" exited with 2.
```

##### Steps to reproduce

build it using travis ci

```
language: cpp
jobs:
  include:
    - name: "Android Client"
      os: linux
      dist: xenial
      install:
        - sudo apt update
        - sudo apt install -y make m4 subversion git-core build-essential realpath openjdk-8-jdk lib32z1
        - wget -O - https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz | tar -xzvC ~
        - export ANDROID_HOME="$HOME/android-sdk-linux"
        - wget -O ~/android-ndk-r16b.zip https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip
        - unzip ~/android-ndk-r16b.zip -d ~
        - rm ~/android-ndk-r16b.zip
        - export ANDROID_NDK_HOME="$HOME/android-ndk-r16b"
        - echo y | ~/android-sdk-linux/tools/android update sdk --no-ui -a --filter platform-tool,android-26,build-tools-26.0.3
      script:
        - mkdir -p /tmp/build
        - pushd /tmp/build
        - git clone --depth 1 https://github.com/minetest/minetest.git ./minetest
        - git clone --depth=1 https://github.com/minetest/minetest_game.git ./minetest/games/minetest_game
        - rm -fr ./minetest/games/minetest_game/.git
        - echo "ndk.dir = $ANDROID_NDK_HOME" > ./minetest/build/android/local.properties
        - echo "sdk.dir = $ANDROID_HOME" >> ./minetest/build/android/local.properties
        - pushd ./minetest/build/android
        - make release
        - popd
        - popd
```
